### ISSUE TITLE
Cannot find module 'libphonenumber-js'

### ISSUE THREAD

**Issue by eranabir** [typestack/class-validator#1947]
### Description

just installed class-validator and got this error : 

Cannot find module 'libphonenumber-js'
- C:\Users\user\code\project\api\node_modules\class-validator\cjs\decorator\string\IsPhoneNumber.js

**Minimal code-snippet showcasing the problem**
 

```ts

```

**Comment by kf6kjg** [comment]
IMO the correct solution for this problem is to fix `libphonenumber-js` to export ESM and CJS correctly.  A workaround would be to do as the CLI suggests and use `const asdf = await import("libphonenumber-js")` in this codebase. Another workaround is to set `"skipLibCheck": true` in your `tsconfig.json`.

**Comment by hfhchan-plb** [comment]
It has been fixed 1 week ago in upstream. Upgrading libphonenumber-js to 1.10.41 fixes the issue.

See: https://gitlab.com/catamphetamine/libphonenumber-js/-/commit/d383ce6ccac6aa5ba8bed6ceebb2f66028f4b317

**Comment by PS1TD** [comment]
Still getting same error when `"module": "nodenext"` and using `class-validator@0.14.0` and `libphonenumber-js@1.10.48`
```
node_modules/.pnpm/libphonenumber-js@1.10.48/node_modules/libphonenumber-js/index.d.cts:18:8 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("./types.d.js")' call instead.

18 } from './types.d.js';
          ~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/libphonenumber-js@1.10.48/node_modules/libphonenumber-js/index.d.cts:18
```

Setting `"skipLibCheck": true` in tsconfig works, but I am not happy with such a solution
